---
kind: pipeline
name: puppet7

platform:
  os: linux
  arch: amd64

steps:
- name: 2.7.2-Puppet ~> 7
  image: ruby:2.7.2
  commands:
  - bundle install
  - bundle exec rake validate lint check rubocop
  - bundle exec rake parallel_spec

---
kind: pipeline
name: puppet6

platform:
  os: linux
  arch: amd64

steps:
- name: 2.5.6-Puppet ~> 6
  image: ruby:2.5.7

  commands:
  - bundle install
  - bundle exec rake validate lint check rubocop
  - bundle exec rake parallel_spec

---
kind: pipeline
name: integration

steps:
- name: include
  image: puppet/puppet-agent:latest
  commands:
  - cd ..
  - ls
  - pwd
  - puppet apply --modulepath=`pwd` -e "include yggdrasil"


