---
kind: pipeline
name: syntax

platform:
  os: linux
  arch: amd64

steps:
- name: validate lint check rubocop-Ruby 2.7.2-Puppet ~> 7
  image: ruby:2.7.2
  commands:
  - bundle install
  - bundle exec rake validate lint check rubocop

---
kind: pipeline
name: unit

platform:
  os: linux
  arch: amd64

steps:
- name: parallel_spec-Ruby 2.7.2-Puppet ~> 7
  image: ruby:2.7.2
  commands:
  - bundle install
  - bundle exec rake parallel_spec

depends_on:
- syntax

